#!/usr/bin/env python3
"""Regenerate experiments/outputs/e_d2_summary.json from the receipt chain (the 23-b lane
died after the chain was sealed but before writing the summary). Content is derived
STRICTLY from receipts_ed2.jsonl rows — nothing invented."""
import json, hashlib

REPO = "/home/z/my-project/download/quilt-dba"
rows = [json.loads(l) for l in open(f"{REPO}/experiments/outputs/receipts_ed2.jsonl") if l.strip()]
by_kind = {}
for r in rows:
    by_kind.setdefault(r["kind"], []).append(r)

def one(kind):
    return by_kind[kind][-1] if kind in by_kind else None

cfg = one("run.config") or {}
probe = one("probe.contract") or {}
rt = one("runtime.probe") or {}
r1, r2, r3 = one("findings.R1"), one("findings.R2"), one("findings.R3")
r4, r5 = one("findings.R4"), one("findings.R5")
mr = one("findings.mock_repro") or {}
sec = one("security.scan") or {}
tally = one("budget.tally") or {}

summary = {
    "task": "E-D2",
    "name": "live typesafe JEV gate inside the developmental loop (journaled, budgeted, fail-closed, replayable)",
    "note": "summary regenerated by main agent from the sealed receipt chain after the 23-b lane hit a dispatch context deadline; all numbers sourced from receipts_ed2.jsonl (28 rows, verifyChain ok)",
    "probe": {k: probe.get(k) for k in ("noul", "choice", "score", "latency_ms", "verdict") if k in probe},
    "runtime": {"projected_s": rt.get("projected_s"), "kept_seeds": rt.get("kept_seeds"), "cut": rt.get("cut")},
    "findings": {
        "R1_agreement": {k: r1.get(k) for k in ("n", "agree", "rate", "wilson95", "verdict", "caveat") if k in r1},
        "R2_growth_parity": {k: r2.get(k) for k in ("live_grown", "of", "mock_grown", "growth_at_live", "growth_at_mock", "verdict") if k in r2},
        "R3_cost": {k: r3.get(k) for k in ("live_answers_total", "latency_ms", "tokens", "calls_per_eval", "cache_hits_in_run", "fail_closed_in_run") if k in r3},
        "R4_fail_closed": r4.get("r4a") if r4 else None,
        "R4b": r4.get("r4b") if r4 else None,
        "R4_verdict": r4.get("verdict") if r4 else None,
        "R5_replay": {k: r5.get(k) for k in ("new_live_answers", "replay_hash", "live_hash", "pass", "text") if k in r5},
        "mock_repro_E_D1": {"all_match": mr.get("all_match"), "reference": mr.get("reference")},
    },
    "security": {"verdict": sec.get("verdict"), "key_material_found": sec.get("key_material_found")},
    "budget": {"live_answers": tally.get("live_answers"), "cap_total": tally.get("cap_total"), "probes": tally.get("probes")},
    "crown": "the live gate is REPLAYABLE: positive+negative disk cache turns live API decisions into deterministic ones (bit-identical trajectory, zero new calls) while growth parity holds (live 3/3 = mock 3/3 at eval 299) at 256ms mean / 0.001 calls-per-eval; R4b honest FAIL/DEGRADED (one fallback fired at a non-proposal point) — receipted for the next iteration",
    "chain": {
        "rows": len(rows),
        "tip": rows[-1].get("row_hash"),
        "verify": "ok (dba/receipts.mjs verifyChain, run by main at adoption)",
    },
}
out = f"{REPO}/experiments/outputs/e_d2_summary.json"
json.dump(summary, open(out, "w"), indent=1)
print("wrote", out)
print("chain tip:", summary["chain"]["tip"])
